trigger:
- deploy

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0

  displayName: 'Use Node version 14x'

  inputs:

    versionSpec: 14.x

    checkLatest: true

- task: YarnInstaller@3

  displayName: 'Intall Yarn'

  inputs:

    versionSpec: '1.x'

    checkLatest: true

- task: Yarn@3

  displayName: 'Install dependencies'

  inputs:

    projectDirectory: '$(System.DefaultWorkingDirectory)'

    arguments: 'yarn install'

    productionMode: true


- task: Yarn@3

  displayName: 'Build'

  inputs:

    projectDirectory: '$(System.DefaultWorkingDirectory)'

    arguments: 'run build'

- task: CopyFiles@2

  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'

  inputs:

    Contents: 'build/**'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    OverWrite: true

- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'

  
